/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.luthfipun.ytupload

import github.luthfipun.ytupload.youtube.Upload

fun main() {
    val upload = Upload()
    upload.startUpload()
}